#!/usr/bin/env python
from subprocess import PIPE, run
import sys
try:
  from yachalk import chalk
except ImportError:
  class Chalk:
    def red(self, text: str) -> str:
      return text
  chalk = Chalk()

prefix_length = 7

staged_files = run(["git", "diff", "--name-only", "--cached"], stdout=PIPE).stdout.decode("utf8").splitlines()

files_with_conflicts = []
for staged_file in staged_files:
  show_result = run(["git", "show", ":" + staged_file], stdout=PIPE)
  file_contents = show_result.stdout.decode("utf8").splitlines()
  for line in file_contents:
    if len(line) >= prefix_length:
      prefix = line[:prefix_length]
      if prefix in ("<" * prefix_length, "=" * prefix_length, ">" * prefix_length):
        files_with_conflicts += [staged_file]
        break

if files_with_conflicts:
  print(f"There are {chalk.red(len(files_with_conflicts))} file(s) {chalk.red('with conflicts')}:", file=sys.stderr)
  files_with_conflicts.sort()
  for file_with_conflicts in files_with_conflicts:
    print(f"\t{file_with_conflicts}", file=sys.stderr)

sys.exit(1 if files_with_conflicts else 0)
